name: Build and Deploy
on:
  push:
    branches:
    - dev
    paths-ignore:
      - 'decision-records/**'
      - '.vscode/**'
  release:
    types:
    - published

env:
  NODE_VERSION: 16.x

permissions:
  contents: read

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout Source

    - name: Set up NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm

    - name: Restore
      run: npm install

    - name: Build
      run: npm run build -- --mode=production

    - name: Create Web App Deployment Package
      uses: ihiroky/archive-action@v1
      with:
        root_dir: ./out/app
        file_path: ./package/WebApp.zip

    - name: Create Functions App Deployment Package
      uses: ihiroky/archive-action@v1
      with:
        root_dir: ./out/functions
        file_path: ./package/FunctionsApp.zip

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Application
        path: ./package/*.zip

  deploy-test:
    name: Deploy on Test Environment
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Test
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      with:
        name: Application

    - name: Deploy Azure WebApp
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: littlefinger-test
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: contoso.azurecr.io/nodejssampleapp:${{ github.sha }}
        package: WebApp.zip

    - name: Deploy Azure Functions App
      uses: Azure/functions-action@v1
      with:
        app-name: littlefinger-functions-test
        publish-profile: ${{ secrets.AZURE_FUNCTIONS_APP_PUBLISH_PROFILE }}
        package: FunctionsApp.zip

  deploy-release:
    name: Deploy on Release Environment
    if: github.event_name == 'release'
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Release
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      with:
        name: Application

    - name: Deploy Azure WebApp
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: littlefinger
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: contoso.azurecr.io/nodejssampleapp:${{ github.sha }}
        package: WebApp.zip

    - name: Deploy Azure Functions App
      uses: Azure/functions-action@v1
      with:
        app-name: littlefinger-functions
        publish-profile: ${{ secrets.AZURE_FUNCTIONS_APP_PUBLISH_PROFILE }}
        package: FunctionsApp.zip